version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /node_modules
    env_file:
      - ./frontend/.env
    environment:
      - REACT_APP_API_URL=http://localhost:8000
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/main
    env_file:
      - ./backend/.env
    environment:
      - ENVIRONMENT=development
      - PYTHONPATH=/main
      - PYTHONUNBUFFERED=1
      - ML_API_URL=http://host.docker.internal:8001
      - ML_SERVICE_URL=http://host.docker.internal:8001 